### PR TITLE
Update pkg name

### PR DESCRIPTION
**Pull request by cnkarz**
# PR Description

Update pkg name

Fixes # (issue)

## Type of change

Update pkg name

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cnkarz** [comment]
[@engineering-team](!subteam^S037LU0GUAF) :pray:

**Comment by gjaldon** [comment]
@cnkarz looks like the build has failed due to the change in package name. Should there be more updates done to fix this?

**Comment by cnkarz** [comment]
no I think they are due to packages being too old. If I try to update them, it won't work

**Comment by cnkarz** [comment]
found another way without updating this repo

**Pull request closed without merging**
